disabled_rules:
    - line_length
    - todo
    # We'd like to use "db" as an identifier.
    - identifier_name
    # Hydrus uses "master" terminology everywhere.
    - inclusive_language

    # These rules clash with SwiftFormat:
    - trailing_comma
    - closure_parameter_position
    - opening_brace
