excluded:
    - Pods
disabled_rules:
    - line_length
    - todo
    # We'd like to use "db" as an identifier.
    - identifier_name
    # Hydrus uses "master" terminology everywhere.
    - inclusive_language
analyzer_rules:
    - explicit_self
